BIN_DIR = ../Bin

NETEXE_NAME = UserTracker.net

SRC_FILES = \
	./*.cs \
	../Res/AssemblyInfo-OpenNI.cs

USED_LIBS = OpenNI.net
CSFLAGS = -unsafe
NET_WIN_FORMS = 1

LIB_DIRS += ../../Lib
include ../Build/Common/CommonCSMakefile
