BIN_DIR = ../Bin

SRC_FILES = \
	./org/OpenNI/Samples/SimpleViewer/*.java

JAR_NAME = org.OpenNI.Samples.SimpleViewer
USED_JARS = org.OpenNI
MAIN_CLASS = org.OpenNI.Samples.SimpleViewer.SimpleViewerApplication

LIB_DIRS += ../../Lib
include ../Build/Common/CommonJavaMakefile
