BIN_DIR = ../Bin

SRC_FILES = \
	./org/OpenNI/Samples/SimpleRead/*.java

JAR_NAME = org.OpenNI.Samples.SimpleRead
USED_JARS = org.OpenNI
MAIN_CLASS = org.OpenNI.Samples.SimpleRead.SimpleRead

LIB_DIRS += ../../Lib
include ../Build/Common/CommonJavaMakefile



