//
//  enumNames.c
//  AlphaTestTexture
//
//  Created by Joshua Fisher on 7/25/11.
//  Copyright 2011 Potion Design. All rights reserved.
//

#include "poEnums.h"

#define X(name) [name] = #name

// this is some weird stuff from C99
const char *fit_name[] = {
	X(PO_TEX_FIT_NONE),
	X(PO_TEX_FIT_EXACT),
	X(PO_TEX_FIT_H),
	X(PO_TEX_FIT_V),
	X(PO_TEX_FIT_INSIDE)
};

const char *alg_name[] = {
	X(PO_ALIGN_TOP_LEFT),
	X(PO_ALIGN_TOP_CENTER),
	X(PO_ALIGN_TOP_RIGHT),
	X(PO_ALIGN_CENTER_LEFT),
	X(PO_ALIGN_CENTER_CENTER),
	X(PO_ALIGN_CENTER_RIGHT),
	X(PO_ALIGN_BOTTOM_LEFT),
	X(PO_ALIGN_BOTTOM_CENTER),
	X(PO_ALIGN_BOTTOM_RIGHT)
};

const char *evt_name[] = {
	X(PO_TOUCH_BEGAN_EVENT),
	X(PO_TOUCH_ENDED_EVENT),
	X(PO_TOUCH_MOVED_EVENT),
	
	X(PO_KEY_UP_EVENT),
	X(PO_KEY_DOWN_EVENT),
	
	X(PO_KEY_PRESS_EVENT),
	X(PO_KEY_RELEASE_EVENT),
	
	X(PO_MOUSE_UP_INSIDE_EVENT),
	X(PO_MOUSE_UP_OUTSIDE_EVENT),
	X(PO_MOUSE_UP_EVERYWHERE_EVENT),
	
	X(PO_MOUSE_DOWN_INSIDE_EVENT),
	X(PO_MOUSE_DOWN_OUTSIDE_EVENT),
	X(PO_MOUSE_DOWN_EVERYWHERE_EVENT),
	
	X(PO_MOUSE_MOVE_EVENT),
	
	X(PO_MOUSE_DRAG_EVENT),
	X(PO_MOUSE_DRAG_EVERYWHERE_EVENT),
	
	X(PO_MOUSE_ENTER_EVENT),
	X(PO_MOUSE_OVER_EVENT),
	X(PO_MOUSE_LEAVE_EVENT),
	
	X(PO_WINDOW_RESIZED_EVENT),
	
	X(PO_LAST_EVENT)
};



