BIN_DIR = ../Bin

INC_DIRS = ../../Include =/usr/include/ni

SRC_FILES = ./*.cpp

EXE_NAME = Sample-NiSimpleCreate
USED_LIBS = OpenNI

LIB_DIRS += ../../Lib
include ../Build/Common/CommonCppMakefile

