#pragma once

enum poOrientation {
	PO_VERTICAL,
	PO_HORIZONTAL
};

enum poAlignment {
	PO_ALIGN_TOP_LEFT,
	PO_ALIGN_TOP_CENTER,
	PO_ALIGN_TOP_RIGHT,
	PO_ALIGN_CENTER_LEFT,
	PO_ALIGN_CENTER_CENTER,
	PO_ALIGN_CENTER_RIGHT,
	PO_ALIGN_BOTTOM_LEFT,
	PO_ALIGN_BOTTOM_CENTER,
	PO_ALIGN_BOTTOM_RIGHT,
	
	PO_ALIGN_NUM_OPTIONS
};

enum poTextureScaleOption {
	PO_TEX_OBJ_RESHAPE=0,
	PO_TEX_NO_FIT=1,
	PO_TEX_FIT_H=2,
	PO_TEX_FIT_V=3,
	PO_TEX_FIT_MIN=4,
	PO_TEX_FIT_MAX=5
};

enum poStrokePlacementOption {
	PO_STROKE_INSIDE=0,
	PO_STROKE_OUTSIDE,
	PO_STROKE_CENTER
};

enum poWindowType {
	WINDOW_TYPE_NORMAL = 0,
	WINDOW_TYPE_BORDERLESS = 1,
	WINDOW_TYPE_FULLSCREEN = 2
};

enum VertexAttribute {
	ATTRIB_POINT = 0,
	ATTRIB_COLOR = 1,
	ATTRIB_TEX_COORD = 2,
};

enum StrokeCapProperty {
	STROKE_CAP_BUTT = 0,
	STROKE_CAP_ROUND = 1,
	STROKE_CAP_SQUARE = 2
};

enum StrokeJoinProperty {
	STROKE_JOIN_MITRE = 0,
	STROKE_JOIN_BEVEL = 1,
	STROKE_JOIN_ROUND = 2
};

