#pragma once

enum poOrientation {
	PO_VERTICAL=0,
	PO_HORIZONTAL
};

enum poAlignment {
	PO_ALIGN_TOP_LEFT=0,
	PO_ALIGN_TOP_CENTER,
	PO_ALIGN_TOP_RIGHT,
	PO_ALIGN_CENTER_LEFT,
	PO_ALIGN_CENTER_CENTER,
	PO_ALIGN_CENTER_RIGHT,
	PO_ALIGN_BOTTOM_LEFT,
	PO_ALIGN_BOTTOM_CENTER,
	PO_ALIGN_BOTTOM_RIGHT,
	
	PO_ALIGN_NUM_OPTIONS
};

enum poTextureFitOption {
	PO_TEX_FIT_NONE=0,
	PO_TEX_FIT_EXACT,
	PO_TEX_FIT_H,
	PO_TEX_FIT_V,
	PO_TEX_FIT_INSIDE,
	
	PO_TEX_FIT_NUM_OPTIONS
};

enum poStrokePlacementOption {
	PO_STROKE_INSIDE=0,
	PO_STROKE_OUTSIDE,
	PO_STROKE_CENTER
};

enum poWindowType {
	WINDOW_TYPE_NORMAL=0,
	WINDOW_TYPE_BORDERLESS,
	WINDOW_TYPE_FULLSCREEN
};

enum VertexAttribute {
	ATTRIB_POINT=1,
	ATTRIB_COLOR=2,
	ATTRIB_TEX_COORD=4,
};

enum StrokePlacementProperty {
	STROKE_PLACE_INSIDE=0,
	STROKE_PLACE_OUTSIDE,
	STROKE_PLACE_CENTER
};

enum StrokeCapProperty {
	STROKE_CAP_BUTT=0,
	STROKE_CAP_ROUND,
	STROKE_CAP_SQUARE
};

enum StrokeJoinProperty {
	STROKE_JOIN_MITRE=0,
	STROKE_JOIN_BEVEL,
	STROKE_JOIN_ROUND
};


