BIN_DIR = ../Bin

SRC_FILES = \
	./org/OpenNI/Samples/UserTracker/*.java

JAR_NAME = org.OpenNI.Samples.UserTracker
USED_JARS = org.OpenNI
MAIN_CLASS = org.OpenNI.Samples.UserTracker.UserTrackerApplication

LIB_DIRS += ../../Lib
include ../Build/Common/CommonJavaMakefile
